"""Pydantic models for placement test structured outputs."""

from __future__ import annotations

from pydantic import BaseModel, Field


class PlacementQuestion(BaseModel):
    """A placement test question generated by the LLM."""

    question: str
    question_type: str  # multiple_choice, fill_blank, essay, speaking
    options: list[str] = Field(default_factory=list)
    correct_answer: str | None = None
    scenario: str | None = None  # for listening
    passage: str | None = None  # for reading
    instructions: str | None = None
    min_words: int | None = None
    max_words: int | None = None


class PlacementEvaluation(BaseModel):
    """Full placement test evaluation."""

    listening_band: float = Field(ge=0, le=9)
    reading_band: float = Field(ge=0, le=9)
    writing_band: float = Field(ge=0, le=9)
    speaking_band: float = Field(ge=0, le=9)
    overall_band: float = Field(ge=0, le=9)
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    focus_areas: list[str] = Field(default_factory=list)
    section_analysis: dict[str, str] = Field(default_factory=dict)
    feedback_markdown: str = ""
