"""Pydantic models for the IELTS exam agent structured outputs."""

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Question generation
# ---------------------------------------------------------------------------

class ExamQuestion(BaseModel):
    """A single IELTS exam question generated by the LLM."""

    section: Literal["speaking", "writing", "reading", "listening"] = Field(
        description="IELTS section"
    )
    part: int = Field(description="Part/section number within the section")
    question_text: str = Field(description="Full question or task prompt")
    question_type: str = Field(
        description="e.g. 'cue_card', 'discussion', 'essay', 'multiple_choice', …"
    )
    time_limit_seconds: Optional[int] = Field(
        None, description="Time limit for this question"
    )
    cue_card: Optional[str] = Field(
        None, description="Cue card content (Speaking Part 2 only)"
    )
    options: Optional[List[str]] = Field(
        None, description="Answer options (reading/listening MCQ)"
    )
    correct_answer: Optional[str] = Field(
        None, description="Correct answer (reading/listening only)"
    )
    scoring_notes: Optional[str] = Field(
        None, description="Notes for the evaluator on what to look for"
    )


# ---------------------------------------------------------------------------
# Individual answer evaluation
# ---------------------------------------------------------------------------

class AnswerEvaluation(BaseModel):
    """Evaluation of one candidate answer."""

    question_number: int = Field(description="Which question this evaluates")
    band_score: float = Field(
        description="Band score for this answer (0-9, half increments)", ge=0, le=9
    )
    # IELTS band descriptors ------------------------------------------------
    task_achievement: float = Field(
        ge=0, le=9,
        description="Task Achievement / Task Response (Writing) or Fluency & Coherence (Speaking)",
    )
    coherence_cohesion: float = Field(
        ge=0, le=9,
        description="Coherence and Cohesion",
    )
    lexical_resource: float = Field(
        ge=0, le=9,
        description="Lexical Resource – range and accuracy of vocabulary",
    )
    grammatical_range: float = Field(
        ge=0, le=9,
        description="Grammatical Range and Accuracy",
    )
    pronunciation: Optional[float] = Field(
        None, ge=0, le=9,
        description="Pronunciation (Speaking only)",
    )
    strengths: List[str] = Field(default_factory=list)
    weaknesses: List[str] = Field(default_factory=list)
    suggestions: List[str] = Field(default_factory=list)
    feedback: str = Field(description="Detailed narrative feedback")


# ---------------------------------------------------------------------------
# Final exam report
# ---------------------------------------------------------------------------

class SectionScore(BaseModel):
    """Band score for one section."""

    section: str
    band_score: float = Field(ge=0, le=9)
    detail: str = Field(description="Brief justification")


class FinalExamReport(BaseModel):
    """Comprehensive IELTS exam evaluation."""

    individual_evaluations: List[AnswerEvaluation] = Field(
        description="Per-question evaluations"
    )
    section_scores: List[SectionScore] = Field(
        description="Per-section band scores"
    )
    overall_band: float = Field(
        ge=0, le=9,
        description="Overall IELTS band score (average of sections, rounded to nearest 0.5)",
    )
    strengths: List[str] = Field(default_factory=list)
    weaknesses: List[str] = Field(default_factory=list)
    recommendations: List[str] = Field(
        default_factory=list,
        description="Actionable study recommendations",
    )
    final_report_markdown: str = Field(
        description="Full report in markdown format"
    )
